Repository running-23/pickable, pull requests merged in 2022-04, with the labels that each got.

#49 マイページでのイベント表示を過去と現在以降でそれぞれ表示する
  .rubocop.yml
  app/controllers/events_controller.rb
  app/controllers/users_controller.rb
  app/models/application_record.rb
  app/models/event.rb
  app/views/events/index.html.erb
  app/views/events/show.html.erb
  app/views/users/_event.html.erb
  app/views/users/show.html.erb
Labels: 機能追加

#56 ひよコネURLに入る値を制御する
  app/models/user.rb
Labels: バグ, リファクタリング

#57 feat: githubログインを本番環境でも実装
  .gitignore
  config/credentials/production.yml.enc
Labels: 機能追加

#59 Pickable機能追加
  app/assets/images/pick.png
  app/controllers/events_controller.rb
  app/controllers/pickables_controller.rb
  app/views/events/index.html.erb
  app/views/events/show.html.erb
  config/routes.rb
  db/seeds.rb
  spec/requests/pickables_spec.rb
Labels: 機能追加

#62 Feat: 全体のカラーテーマ、フォントの定義とfont-awesomeの導入 #53
  app/assets/stylesheets/application.scss
  app/javascript/packs/application.js
  app/views/users/edit.html.erb
  package.json
  yarn.lock
Labels: 環境設定, デザイン

#63 Design #53
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/event.scss
  app/views/events/index.html.erb
Labels: デザイン

#66 ユーザー編集ページの完成
  app/assets/images/hiyoconne_icon.png
  app/assets/images/no_hiyoco_icon.PNG
  app/assets/stylesheets/application.scss
  app/models/participation.rb
  app/views/shared/_header.html.erb
  app/views/users/edit.html.erb
  config/locales/model.ja.yml
Labels: デザイン

#68 マイページの完成
  app/assets/stylesheets/application.scss
  app/controllers/users_controller.rb
  app/javascript/packs/application.js
  app/javascript/packs/common.js
  app/models/participation.rb
  app/views/users/edit.html.erb
  app/views/users/show.html.erb
  db/seeds.rb
Labels: リファクタリング, デザイン

#80 no_hiyoco_iconの拡張子をPNGからpngに変更する
  app/assets/images/no_hiyoco_icon.png
Labels: バグ

#81 ひよコネURLの未登録ユーザーが一人いると他のユーザーが未登録で更新できない不具合を解決
  app/models/user.rb
  db/migrate/20220412054124_remove_uniqueness_of_hiyoconne_url.rb
  db/schema.rb
  spec/factories/users.rb
  spec/models/user_spec.rb
Labels: バグ

#83 Pickable機能のエラー解消
  app/assets/stylesheets/application.scss
  app/controllers/participations_controller.rb
  app/controllers/pickables_controller.rb
  app/models/participation.rb
  config/initializers/assets.rb
  package.json
  yarn.lock
Labels: バグ

#86 Design #53
  .rubocop.yml
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/event.scss
  app/controllers/events_controller.rb
  app/models/event.rb
  app/views/events/_form.html.erb
  app/views/events/edit.html.erb
  app/views/events/index.html.erb
  app/views/events/new.html.erb
  app/views/events/show.html.erb
  config/locales/model.ja.yml
Labels: デザイン

#91 メールのレイアウトを修正する
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/mailer.scss
  app/views/mailers/before_event_start_mailer/before_event_start.html.erb
  app/views/mailers/event_cancel_mailer/event_cancel.html.erb
  app/views/mailers/pickable_mailer/report_pickable.html.erb
  app/views/mailers/user_mailer/welcome_email.html.erb
Labels: デザイン

#95 ヘッダーの作成
  app/assets/images/logo.png
  app/assets/stylesheets/application.scss
  app/controllers/users_controller.rb
  app/views/events/index.html.erb
  app/views/shared/_before_login_header.html.erb
  app/views/shared/_event.html.erb
  app/views/shared/_header.html.erb
  app/views/users/edit.html.erb
  app/views/users/show.html.erb
Labels: リファクタリング, デザイン

#93 Pickable発動を1回だけにする
  app/controllers/pickables_controller.rb
  app/models/event.rb
  app/views/events/show.html.erb
  db/migrate/20220413082519_add_column_pickable_counts_to_events.rb
  db/migrate/20220414123335_change_columns_notnull_pickable_counts.rb
  db/schema.rb
  spec/factories/events.rb
  spec/models/event_spec.rb
Labels: バグ

#96 イベント詳細に改行・リンクを表示
  Gemfile
  Gemfile.lock
  app/views/events/show.html.erb
Labels: 機能追加

#97 refactor: エラーメッセージの共通化
  app/assets/stylesheets/application.scss
  app/views/categories/_form.html.erb
  app/views/events/_form.html.erb
  app/views/shared/_error_messages.html.erb
  app/views/users/_form.html.erb
  app/views/users/edit.html.erb
Labels: リファクタリング

#98 Create time #90
  app/controllers/events_controller.rb
  app/models/event.rb
  app/views/events/_form.html.erb
Labels: リファクタリング

#104 参加キャンセル時の確認を追加
  app/views/events/show.html.erb
Labels: デザイン

#105 refactor: ユーザー新規登録時のメール文面, 新規登録時の挙動を修正
  app/assets/stylesheets/mailer.scss
  app/controllers/oauths_controller.rb
  app/views/mailers/before_event_start_mailer/before_event_start.html.erb
  app/views/mailers/user_mailer/welcome_email.html.erb
Labels: デザイン

#106 feat: モーダル機能実装 #87
  app/assets/stylesheets/event.scss
  app/javascript/packs/common.js
  app/views/events/show.html.erb
  app/views/layouts/application.html.erb
Labels: デザイン

#107 Punditによる権限追加
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/categories_controller.rb
  app/policies/application_policy.rb
  app/policies/category_policy.rb
  app/views/events/show.html.erb
Labels: 機能追加

#112 コントローラでのPickable発動回数制限
  app/controllers/pickables_controller.rb
Labels: バグ

#108 Event design #103
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/event.scss
  app/controllers/events_controller.rb
  app/models/event.rb
  app/views/events/show.html.erb
Labels: デザイン

#115 Topページの作成とMVPに向けた調整、およびバグの修正
  app/assets/images/calendar.png
  app/assets/images/connection.png
  app/assets/images/desc_join.png
  app/assets/images/desc_new_event.png
  app/assets/images/desc_settings.png
  app/assets/images/explanation.png
  app/assets/images/man_with_bulb.png
  app/assets/images/use_phone.png
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/event.scss
  app/controllers/events_controller.rb
  app/controllers/pickables_controller.rb
  app/controllers/users_controller.rb
  app/javascript/packs/common.js
  app/models/event.rb
  app/views/events/new.html.erb
  app/views/events/show.html.erb
  app/views/layouts/application.html.erb
  app/views/mailers/before_event_start_mailer/before_event_start.html.erb
  app/views/shared/_before_login_header.html.erb
  app/views/shared/_header.html.erb
  app/views/static_pages/top.html.erb
  app/views/users/_form.html.erb
  app/views/users/edit.html.erb
  app/views/users/show.html.erb
  config/locales/model.ja.yml
  public/favicon.ico
Labels: リファクタリング, デザイン

#117 Change mvp #113
  app/assets/images/pick.png
  app/controllers/users_controller.rb
  app/views/events/show.html.erb
  app/views/users/edit.html.erb
  app/views/users/show.html.erb
Labels: リファクタリング

#118 MVP前の最終調整
  app/models/event.rb
  app/views/events/show.html.erb
  app/views/static_pages/top.html.erb
  app/views/users/edit.html.erb
  app/views/users/show.html.erb
Labels: デザイン

#120 Fix: イベントフォームのカテゴリーのエラーメッセージを修正 #119
  config/locales/model.ja.yml
Labels: バグ

#122 Fix: 他ユーザー詳細ページにそのユーザーの参加イベントが表示されるように修正 #121
  app/controllers/users_controller.rb
  app/models/event.rb
  app/views/events/_form.html.erb
Labels: バグ

#128 ユーザー編集時のカテゴリーを選択を必須に変更
  app/models/event.rb
  app/models/user.rb
  app/views/users/edit.html.erb
  config/locales/model.ja.yml
Labels: バグ

#130 style: 水色ボタンのホバー時の挙動を変更 #126
  app/assets/stylesheets/application.scss
Labels: デザイン

#132 国際化と動的タイトルの実装
  app/controllers/application_controller.rb
  app/controllers/categories_controller.rb
  app/controllers/events_controller.rb
  app/controllers/oauths_controller.rb
  app/controllers/participations_controller.rb
  app/controllers/pickables_controller.rb
  app/controllers/user_sessions_controller.rb
  app/controllers/users_controller.rb
  app/helpers/application_helper.rb
  app/models/event.rb
  app/models/user.rb
  app/views/events/edit.html.erb
  app/views/events/index.html.erb
  app/views/events/new.html.erb
  app/views/events/show.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_before_login_header.html.erb
  app/views/users/_event.html.erb
  app/views/users/edit.html.erb
  app/views/users/show.html.erb
  config/locales/activerecord/ja.yml
  config/locales/views/ja.yml
Labels: リファクタリング, 機能追加

#133 style: Pickable時, イベントキャンセル時のメールのレイアウトを修正する
  app/views/mailers/event_cancel_mailer/event_cancel.html.erb
  app/views/mailers/pickable_mailer/report_pickable.html.erb
Labels: デザイン

#136 Fix: #134とイベント作成時のcategoryバリデーションのエラーメッセージの修正 #134
  app/views/users/show.html.erb
  config/locales/activerecord/ja.yml
Labels: バグ

#135 Add time #127
  app/assets/stylesheets/event.scss
  app/controllers/events_controller.rb
  app/models/event.rb
  app/views/events/_form.html.erb
  app/views/events/show.html.erb
  config/environments/development.rb
  config/locales/activerecord/ja.yml
  config/locales/views/ja.yml
  db/migrate/20220429091521_add_timescale_to_events.rb
  db/schema.rb
  spec/factories/events.rb
  spec/models/event_spec.rb
Labels: 機能追加

#137 終了したイベントでのPickable発動をできないように変更
  app/controllers/pickables_controller.rb
  app/views/events/show.html.erb
  app/views/users/show.html.erb
  config/locales/views/ja.yml
Labels: バグ
