Repository running-23/pickable, pull requests merged in 2022-03, with the labels that each got.

#14 Chore: 環境構築
  .rspec
  .rubocop.yml
  Gemfile
  Gemfile.lock
  Rakefile
  app/javascript/packs/application.js
  app/javascript/stylesheets/application.scss
  app/views/layouts/application.html.erb
  config.ru
  config/application.rb
  config/boot.rb
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/backtrace_silencers.rb
  config/initializers/filter_parameter_logging.rb
  config/locales/en.yml
  config/locales/model.ja.yml
  config/puma.rb
  config/spring.rb
  db/schema.rb
  lib/tasks/auto_annotate_models.rake
  package.json
  spec/rails_helper.rb
  spec/spec_helper.rb
  yarn.lock
Labels: 環境設定

#26 Fix: herokuエラー解消
  app/controllers/application_controller.rb
Labels: バグ

#28 Events setting #24
  Gemfile
  Gemfile.lock
  app/controllers/events_controller.rb
  app/javascript/packs/application.js
  app/javascript/packs/common.js
  app/models/event.rb
  app/models/participation.rb
  app/views/events/_form.html.erb
  app/views/events/index.html.erb
Labels: 機能追加

#34 Feat: カテゴリ管理のテーブルとモデルの作成、及び関連付け
  app/controllers/categories_controller.rb
  app/controllers/events_controller.rb
  app/models/category.rb
  app/models/event.rb
  app/models/user.rb
  app/models/user_category.rb
  app/views/categories/_form.html.erb
  app/views/categories/edit.html.erb
  app/views/categories/index.html.erb
  app/views/categories/new.html.erb
  app/views/categories/show.html.erb
  app/views/events/_form.html.erb
  app/views/events/index.html.erb
  app/views/events/show.html.erb
  config/locales/model.ja.yml
  config/routes.rb
  db/migrate/20220316114836_create_categories.rb
  db/migrate/20220316122405_create_user_categories.rb
  db/migrate/20220318142701_add_ref_to_events.rb
  db/schema.rb
  spec/factories/categories.rb
  spec/factories/events.rb
  spec/factories/user_categories.rb
  spec/models/category_spec.rb
  spec/models/event_spec.rb
  spec/models/user_category_spec.rb
  spec/requests/categories_spec.rb
Labels: 機能追加

#35 githubログイン機能の実装
  .rubocop.yml
  app/controllers/application_controller.rb
  app/controllers/categories_controller.rb
  app/controllers/events_controller.rb
  app/controllers/oauths_controller.rb
  app/controllers/static_pages_controller.rb
  app/controllers/user_sessions_controller.rb
  app/models/authentication.rb
  app/models/user.rb
  app/views/layouts/application.html.erb
  app/views/shared/_before_login_header.html.erb
  app/views/shared/_flash_message.html.erb
  app/views/shared/_header.html.erb
  app/views/static_pages/top.html.erb
  app/views/user_sessions/new.html.erb
  config/credentials.yml.enc
  config/initializers/sorcery.rb
  config/routes.rb
  db/migrate/20220319130117_sorcery_external.rb
  db/migrate/20220320123720_add_avatars_to_users.rb
  db/migrate/20220320211041_change_column_to_null.rb
  db/schema.rb
  spec/factories/authentications.rb
  spec/factories/users.rb
  spec/models/authentication_spec.rb
  spec/models/user_spec.rb
  spec/requests/oauths_spec.rb
  spec/requests/static_pages_spec.rb
  spec/requests/user_sessions_spec.rb
Labels: 機能追加

#38 refactor: githubログイン実装後の懸念点を修正
  app/controllers/user_sessions_controller.rb
  app/models/user.rb
  app/views/shared/_before_login_header.html.erb
  app/views/static_pages/top.html.erb
  app/views/user_sessions/new.html.erb
  config/initializers/sorcery.rb
  config/routes.rb
  db/migrate/20220323063156_add_column_users_to_github_name.rb
  db/migrate/20220323064145_change_column_name_to_users.rb
  db/migrate/20220323065154_remove_column_mattermost_id_to_users.rb
  db/migrate/20220324011540_add_index_github_name_to_users.rb
  db/schema.rb
  spec/factories/users.rb
  spec/models/user_spec.rb
Labels: リファクタリング

#40 イベントへの参加を実装
  app/controllers/events_controller.rb
  app/controllers/participations_controller.rb
  app/models/event.rb
  app/models/user.rb
  app/views/events/show.html.erb
  config/routes.rb
  spec/requests/participations_spec.rb
Labels: 機能追加

#42 Refact events #41
  app/controllers/events_controller.rb
  app/javascript/packs/common.js
  app/models/event.rb
  app/views/events/_form.html.erb
Labels: リファクタリング

#44 ユーザーの詳細、編集機能の実装
  app/controllers/oauths_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/shared/_header.html.erb
  app/views/users/_event.html.erb
  app/views/users/_form.html.erb
  app/views/users/edit.html.erb
  app/views/users/show.html.erb
  config/locales/model.ja.yml
  config/routes.rb
  db/migrate/20220330024219_add_column_to_users.rb
  db/schema.rb
  spec/factories/users.rb
  spec/models/user_spec.rb
Labels: 機能追加
